CREATE TABLE [dbo].[SYS_PARAM_CREATE_TABLE_CLASS](
	[ID] [nvarchar](32) NOT NULL,
	[NO] [nvarchar](50) NULL,
	[NAME] [nvarchar](128) NULL,
	[ID_INDEX] [int] IDENTITY(1,1) NOT NULL,
	[IP] [nvarchar](15) NULL,
	[THE_NAMESPACE] [nvarchar](1000) NULL,
	[FILE_PATH] [nvarchar](1000) NULL,
	[CREATE_DATETIME] [datetime] NULL,
 CONSTRAINT [PK_SYS_PARAM_CREATE_TABLE_CLASS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


