
CREATE TABLE [dbo].[SYS_USER_ROLE_LIST](
	[ID] [nvarchar](32) NOT NULL,
	[NO] [nvarchar](50) NULL,
	[NAME] [nvarchar](128) NULL,
	[SYS_USER_ID] [nvarchar](32) NULL,
	[SYS_ROLE_ID] [nvarchar](32) NULL,
	[CREATE_USER_ID] [nvarchar](32) NULL,
	[CREATE_DATETIME] [datetime] NULL,
	[MODIFY_USER_ID] [nvarchar](32) NULL,
	[MODIFY_DATETIME] [datetime] NULL,
 CONSTRAINT [PK_SYS_USER_ROLE_LIST] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SYS_USER_ROLE_LIST] ADD  CONSTRAINT [DF_SYS_USER_ROLE_LIST_CREATE_DATETIME]  DEFAULT (getdate()) FOR [CREATE_DATETIME]
GO

ALTER TABLE [dbo].[SYS_USER_ROLE_LIST] ADD  CONSTRAINT [DF_SYS_USER_ROLE_LIST_MODIFY_DATETIME]  DEFAULT (getdate()) FOR [MODIFY_DATETIME]
GO

ALTER TABLE [dbo].[SYS_USER_ROLE_LIST]  WITH CHECK ADD  CONSTRAINT [FK_SYS_USER_ROLE_LIST_SYS_ROLE] FOREIGN KEY([SYS_ROLE_ID])
REFERENCES [dbo].[SYS_ROLE] ([ID])
GO

ALTER TABLE [dbo].[SYS_USER_ROLE_LIST] CHECK CONSTRAINT [FK_SYS_USER_ROLE_LIST_SYS_ROLE]
GO

ALTER TABLE [dbo].[SYS_USER_ROLE_LIST]  WITH CHECK ADD  CONSTRAINT [FK_SYS_USER_ROLE_LIST_SYS_USER] FOREIGN KEY([SYS_USER_ID])
REFERENCES [dbo].[SYS_USER] ([ID])
GO

ALTER TABLE [dbo].[SYS_USER_ROLE_LIST] CHECK CONSTRAINT [FK_SYS_USER_ROLE_LIST_SYS_USER]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ID' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SYS_USER_ROLE_LIST', @level2type=N'COLUMN',@level2name=N'ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ÓÃ»§' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SYS_USER_ROLE_LIST', @level2type=N'COLUMN',@level2name=N'SYS_USER_ID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'½ÇÉ«' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SYS_USER_ROLE_LIST', @level2type=N'COLUMN',@level2name=N'SYS_ROLE_ID'
GO


